export type ResourceType =
    | 'wood'
    | 'ore'
    | 'stone'
    | 'tools'
    | 'food'
    | 'bread'
    | 'meat'
    | 'beer'
    | 'wine'
    | 'crystal'
    | 'artifact'
    | 'water'
    | 'grain'
    | 'hops'
    | 'grapes'
    | 'water_lily'
    | 'sand'
    | 'glass';
export type ResourceAmount = { type: ResourceType; amount: number };
