export type ResourceType =
    | 'wood'
    | 'ore'
    | 'stone'
    | 'tools'
    | 'weapons'
    | 'food'
    | 'fish'
    | 'bread'
    | 'meat'
    | 'beer'
    | 'wine'
    | 'water'
    | 'grain'
    | 'hops'
    | 'grapes'
    | 'water_lily'
    | 'sand'
    | 'glass'
    | 'tea'
    | 'pottery'
    | 'spices'
    | 'silk';
export type ResourceAmount = { type: ResourceType; amount: number };
